export const example_response = {
  timestamp: 1683301778070,
  uuid: null,
  status: 200,
  error: null,
  message: "OK",
  managed: true,
  content: {
    summaryCreditsApproved: "79.9%",
    academicCurriculumRisk: [],
    academicCurriculum: [
      {
        title: "Nivel 0",
        courses: [
          {
            codeCourse: "EGN001",
            course: "Ciencias 0",
            idCourse: 1550,
            nameTeacher: "-",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 222,
                namePeriod: "2019 - 1",
                finalNote: 17,
                classroomAverage: 15.6,
                absences: "3.13%",
              },
            ],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "EG0003",
                course: "Matemáticas I",
                idCourse: 923,
              },
              {
                codeCourse: "ME0019",
                course: "Física I",
                idCourse: 924,
              },
            ],
            section: "5",
            credits: 0.0,
            score: "17",
            status: "Aprobado",
            period: "2019 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GHN004",
            course: "Laboratorio de Comunicación 0",
            idCourse: 884,
            nameTeacher: "-",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 222,
                namePeriod: "2019 - 1",
                finalNote: 15,
                classroomAverage: 14.8,
                absences: "6.25%",
              },
            ],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "GH0005",
                course: "Laboratorio de Comunicación 1",
                idCourse: 885,
              },
            ],
            section: "7",
            credits: 0.0,
            score: "15",
            status: "Aprobado",
            period: "2019 - 1",
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 1",
        courses: [
          {
            codeCourse: "CS1100",
            course: "Introducción a la Ciencia de la Computación",
            idCourse: 1055,
            nameTeacher: "-",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 222,
                namePeriod: "2019 - 1",
                finalNote: 15,
                classroomAverage: 12.06,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "CS1102",
                course: "Programación orientada a objetos I",
                idCourse: 1057,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "15",
            status: "Aprobado",
            period: "2019 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EG0003",
            course: "Matemáticas I",
            idCourse: 923,
            nameTeacher: "Chavez Pacheco, Xyoby ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 223,
                namePeriod: "2019 - 2",
                finalNote: 15,
                classroomAverage: 10.9,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EGN001",
                course: "Ciencias 0",
                idCourse: 1550,
              },
            ],
            afterCourses: [
              {
                codeCourse: "EG0005",
                course: "Matemáticas II",
                idCourse: 931,
              },
              {
                codeCourse: "IN0054",
                course: "Estadística y Probabilidades",
                idCourse: 946,
              },
            ],
            section: "2",
            credits: 4.0,
            score: "15",
            status: "Aprobado",
            period: "2019 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EG0004",
            course: "Desafíos Globales",
            idCourse: 928,
            nameTeacher: "-",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 222,
                namePeriod: "2019 - 1",
                finalNote: 16,
                classroomAverage: 15.08,
                absences: ".95%",
              },
            ],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "GH1002",
                course: "Arte y Tecnología",
                idCourse: 460,
              },
              {
                codeCourse: "EG0007",
                course: "Proyectos Interdisciplinarios I",
                idCourse: 947,
              },
            ],
            section: "3",
            credits: 3.0,
            score: "16",
            status: "Aprobado",
            period: "2019 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0005",
            course: "Laboratorio de Comunicación 1",
            idCourse: 885,
            nameTeacher: "Zorrilla Aranguren, Carlos Marcelo",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 223,
                namePeriod: "2019 - 2",
                finalNote: 15,
                classroomAverage: 15.2,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GHN004",
                course: "Laboratorio de Comunicación 0",
                idCourse: 884,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0006",
                course: "Laboratorio de Comunicación 2",
                idCourse: 886,
              },
              {
                codeCourse: "GH0007",
                course: "Introducción al Desarrollo de Empresas",
                idCourse: 887,
              },
            ],
            section: "5",
            credits: 3.0,
            score: "15",
            status: "Aprobado",
            period: "2019 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "ME0019",
            course: "Física I",
            idCourse: 924,
            nameTeacher: "Zegarra Sierra, Katia ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 223,
                namePeriod: "2019 - 2",
                finalNote: 16,
                classroomAverage: 12.9,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EGN001",
                course: "Ciencias 0",
                idCourse: 1550,
              },
            ],
            afterCourses: [
              {
                codeCourse: "ME4003",
                course: "Mecánica de Fluidos",
                idCourse: 40,
              },
              {
                codeCourse: "EN0021",
                course: "Física II",
                idCourse: 932,
              },
            ],
            section: "2",
            credits: 4.0,
            score: "16",
            status: "Aprobado",
            period: "2019 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "QI0027",
            course: "Química General",
            idCourse: 925,
            nameTeacher: "-",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 222,
                namePeriod: "2019 - 1",
                finalNote: 16,
                classroomAverage: 16.6,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "AM0037",
                course: "Ciencia de los Materiales",
                idCourse: 1304,
              },
            ],
            section: "15",
            credits: 3.0,
            score: "16",
            status: "Aprobado",
            period: "2019 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "QI0028",
            course: "Química Experimental",
            idCourse: 930,
            nameTeacher: "-",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 222,
                namePeriod: "2019 - 1",
                finalNote: 14,
                classroomAverage: 15.33,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [],
            section: "5",
            credits: 1.0,
            score: "14",
            status: "Aprobado",
            period: "2019 - 1",
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 2",
        courses: [
          {
            codeCourse: "AM0037",
            course: "Ciencia de los Materiales",
            idCourse: 1304,
            nameTeacher: "Pinedo Flores, Angela ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 223,
                namePeriod: "2019 - 2",
                finalNote: 17,
                classroomAverage: 16.2,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "QI0027",
                course: "Química General",
                idCourse: 925,
              },
            ],
            afterCourses: [],
            section: "1",
            credits: 4.0,
            score: "17",
            status: "Aprobado",
            period: "2019 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CS1102",
            course: "Programación orientada a objetos I",
            idCourse: 1057,
            nameTeacher: "Cuadros Vargas, Ernesto ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 223,
                namePeriod: "2019 - 2",
                finalNote: 16,
                classroomAverage: 13.81,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CS1100",
                course: "Introducción a la Ciencia de la Computación",
                idCourse: 1055,
              },
            ],
            afterCourses: [],
            section: "1",
            credits: 4.0,
            score: "16",
            status: "Aprobado",
            period: "2019 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EG0005",
            course: "Matemáticas II",
            idCourse: 931,
            nameTeacher: "Reynoso Quispe, Patricia ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 241,
                namePeriod: "2020 - 1",
                finalNote: 16,
                classroomAverage: 14.46,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EG0003",
                course: "Matemáticas I",
                idCourse: 923,
              },
            ],
            afterCourses: [
              {
                codeCourse: "ME4003",
                course: "Mecánica de Fluidos",
                idCourse: 40,
              },
              {
                codeCourse: "EG0006",
                course: "Matemáticas III",
                idCourse: 943,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "16",
            status: "Aprobado",
            period: "2020 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EN0021",
            course: "Física II",
            idCourse: 932,
            nameTeacher: "Castillo Ruiz, Oscar Eduardo",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 341,
                namePeriod: "2020 - 0",
                finalNote: 14,
                classroomAverage: 11.67,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "ME0019",
                course: "Física I",
                idCourse: 924,
              },
            ],
            afterCourses: [
              {
                codeCourse: "ME3003",
                course: "Estática",
                idCourse: 480,
              },
              {
                codeCourse: "ME0021",
                course: "Termodinámica",
                idCourse: 945,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "14",
            status: "Aprobado",
            period: "2020 - 0",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0006",
            course: "Laboratorio de Comunicación 2",
            idCourse: 886,
            nameTeacher: "Carrillo Pastor, Giuliana Maria",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 241,
                namePeriod: "2020 - 1",
                finalNote: 17,
                classroomAverage: 14,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0005",
                course: "Laboratorio de Comunicación 1",
                idCourse: 885,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0009",
                course: "Perú: ¿País Industrial?",
                idCourse: 889,
              },
              {
                codeCourse: "GH0010",
                course: "Ética y tecnología",
                idCourse: 890,
              },
              {
                codeCourse: "GH0018",
                course: "Introducción a Neurociencias",
                idCourse: 898,
              },
              {
                codeCourse: "GH0017",
                course: "Introducción al Quechua",
                idCourse: 903,
              },
            ],
            section: "2",
            credits: 3.0,
            score: "17",
            status: "Aprobado",
            period: "2020 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0007",
            course: "Introducción al Desarrollo de Empresas",
            idCourse: 887,
            nameTeacher: "Centty Gutierrez, Yessica Maria",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 241,
                namePeriod: "2020 - 1",
                finalNote: 16,
                classroomAverage: 14.63,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0005",
                course: "Laboratorio de Comunicación 1",
                idCourse: 885,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0008",
                course: "Gestión de Empresas",
                idCourse: 888,
              },
            ],
            section: "9",
            credits: 2.0,
            score: "16",
            status: "Aprobado",
            period: "2020 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH1002",
            course: "Arte y Tecnología",
            idCourse: 460,
            nameTeacher: "Gisbert Carbonell, Ferran ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 341,
                namePeriod: "2020 - 0",
                finalNote: 19,
                classroomAverage: 19,
                absences: "12.5%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EG0004",
                course: "Desafíos Globales",
                idCourse: 928,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0024",
                course: "Crítica de la Modernidad",
                idCourse: 1527,
              },
            ],
            section: "1",
            credits: 1.0,
            score: "19",
            status: "Aprobado",
            period: "2020 - 0",
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 3",
        courses: [
          {
            codeCourse: "CI0002",
            course: "Geometría Descriptiva",
            idCourse: 1554,
            nameTeacher: "Fantozzi Freire, Valeria Maria",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 16,
                classroomAverage: 13.35,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [],
            section: "1",
            credits: 4.0,
            score: "16",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EG0006",
            course: "Matemáticas III",
            idCourse: 943,
            nameTeacher: "Pantoja Carhuavilca, Hermes Yesser",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 18,
                classroomAverage: 16.52,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EG0005",
                course: "Matemáticas II",
                idCourse: 931,
              },
            ],
            afterCourses: [],
            section: "1",
            credits: 4.0,
            score: "18",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EG0007",
            course: "Proyectos Interdisciplinarios I",
            idCourse: 947,
            nameTeacher: "Sabina Rehman, Sara ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 241,
                namePeriod: "2020 - 1",
                finalNote: 16,
                classroomAverage: 14.5,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EG0004",
                course: "Desafíos Globales",
                idCourse: 928,
              },
            ],
            afterCourses: [
              {
                codeCourse: "EG0008",
                course: "Proyectos Interdisciplinarios II",
                idCourse: 949,
              },
            ],
            section: "14",
            credits: 2.0,
            score: "16",
            status: "Aprobado",
            period: "2020 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0008",
            course: "Gestión de Empresas",
            idCourse: 888,
            nameTeacher: "Caycho Chang, Luis Oswaldo",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 19,
                classroomAverage: 17.86,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0007",
                course: "Introducción al Desarrollo de Empresas",
                idCourse: 887,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0011",
                course: "Innovación y Desarrollo de Productos",
                idCourse: 891,
              },
              {
                codeCourse: "GH0019",
                course: "Emprendedores en Acción",
                idCourse: 899,
              },
              {
                codeCourse: "GH0032",
                course: "Startup Lab",
                idCourse: 1797,
              },
            ],
            section: "1",
            credits: 2.0,
            score: "19",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0009",
            course: "Perú: ¿País Industrial?",
            idCourse: 889,
            nameTeacher: "Gonzales Lombardi, Andrea ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 13,
                classroomAverage: 13.71,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0006",
                course: "Laboratorio de Comunicación 2",
                idCourse: 886,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0012",
                course: "Economías en Desarrollo",
                idCourse: 892,
              },
            ],
            section: "2",
            credits: 2.0,
            score: "13",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "IN0054",
            course: "Estadística y Probabilidades",
            idCourse: 946,
            nameTeacher: "Molina Carabaño, Brigida Coromoto",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 402,
                namePeriod: "2021 - 1",
                finalNote: 15,
                classroomAverage: 12.67,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EG0003",
                course: "Matemáticas I",
                idCourse: 923,
              },
            ],
            afterCourses: [
              {
                codeCourse: "AM0038",
                course: "Hidrología",
                idCourse: 1574,
              },
            ],
            section: "2",
            credits: 4.0,
            score: "15",
            status: "Aprobado",
            period: "2021 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "ME0021",
            course: "Termodinámica",
            idCourse: 945,
            nameTeacher: "Lopez Rodriguez, Naudy Ricardo",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 241,
                namePeriod: "2020 - 1",
                finalNote: 17,
                classroomAverage: 12.75,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EN0021",
                course: "Física II",
                idCourse: 932,
              },
            ],
            afterCourses: [],
            section: "2",
            credits: 4.0,
            score: "17",
            status: "Aprobado",
            period: "2020 - 1",
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 4",
        courses: [
          {
            codeCourse: "CI0001",
            course: "Introducción a la Ingeniería Civil",
            idCourse: 1555,
            nameTeacher: "Flores Barron, Giancarlo Augusto",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 15,
                classroomAverage: 15.48,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "CI0007",
                course: "Geodesia Satelital y Fotogrametría",
                idCourse: 1560,
              },
              {
                codeCourse: "CI0008",
                course: "Tecnología de los Materiales de Construcción",
                idCourse: 1561,
              },
              {
                codeCourse: "CI0010",
                course: "Diseño de Infraestructura",
                idCourse: 1563,
              },
              {
                codeCourse: "CI0011",
                course: "Ingeniería de Transporte I",
                idCourse: 1564,
              },
              {
                codeCourse: "CI0012",
                course: "Mecánica de Suelos",
                idCourse: 1565,
              },
              {
                codeCourse: "CI0013",
                course: "Planeamiento de Proyectos de Construcción",
                idCourse: 1566,
              },
            ],
            section: "1",
            credits: 3.0,
            score: "15",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0003",
            course:
              "Tecnologías Aplicadas y Mega Proyectos en Ingeniería Civil",
            idCourse: 1556,
            nameTeacher: "Vilcapoma La Rosa, Alejandro Martin",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 19,
                classroomAverage: 18.17,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [],
            section: "1",
            credits: 3.0,
            score: "19",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0004",
            course: "Geomática",
            idCourse: 1557,
            nameTeacher: "GUERRERO ASMAD, LEO RAYMUNDO",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 402,
                namePeriod: "2021 - 1",
                finalNote: 16,
                classroomAverage: 17.5,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "CI0007",
                course: "Geodesia Satelital y Fotogrametría",
                idCourse: 1560,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "16",
            status: "Aprobado",
            period: "2021 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EG0008",
            course: "Proyectos Interdisciplinarios II",
            idCourse: 949,
            nameTeacher: "Furukawa Fukuda, Roberto Sumiyoshi",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 19,
                classroomAverage: 17,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EG0007",
                course: "Proyectos Interdisciplinarios I",
                idCourse: 947,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0015",
                course: "Imagen y Marca Personal",
                idCourse: 895,
              },
              {
                codeCourse: "EG0009",
                course: "Proyectos Interdisciplinarios III",
                idCourse: 959,
              },
            ],
            section: "18",
            credits: 2.0,
            score: "19",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0010",
            course: "Ética y tecnología",
            idCourse: 890,
            nameTeacher: "Millán Falconí, Armando ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 16,
                classroomAverage: 15.25,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0006",
                course: "Laboratorio de Comunicación 2",
                idCourse: 886,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0015",
                course: "Imagen y Marca Personal",
                idCourse: 895,
              },
            ],
            section: "2",
            credits: 2.0,
            score: "16",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0011",
            course: "Innovación y Desarrollo de Productos",
            idCourse: 891,
            nameTeacher: "Carrazco Cuadros, Rolando Moises",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 402,
                namePeriod: "2021 - 1",
                finalNote: 19,
                classroomAverage: 19,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0008",
                course: "Gestión de Empresas",
                idCourse: 888,
              },
            ],
            afterCourses: [],
            section: "2",
            credits: 2.0,
            score: "19",
            status: "Aprobado",
            period: "2021 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0012",
            course: "Economías en Desarrollo",
            idCourse: 892,
            nameTeacher: "Hoyos Pascual, Dany Manuel",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 401,
                namePeriod: "2021 - 0",
                finalNote: 18,
                classroomAverage: 18.33,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0009",
                course: "Perú: ¿País Industrial?",
                idCourse: 889,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0014",
                course: "Culturas de Gobernanza y Distribución de Poder",
                idCourse: 894,
              },
              {
                codeCourse: "GH0020",
                course: "Behavioral Economics",
                idCourse: 900,
              },
            ],
            section: "1",
            credits: 3.0,
            score: "18",
            status: "Aprobado",
            period: "2021 - 0",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "ME3003",
            course: "Estática",
            idCourse: 480,
            nameTeacher: "Morales Ortiz, Jorge Arturo",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 241,
                namePeriod: "2020 - 1",
                finalNote: 18,
                classroomAverage: 16,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EN0021",
                course: "Física II",
                idCourse: 932,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0005",
                course: "Dinámica",
                idCourse: 1558,
              },
              {
                codeCourse: "CI0006",
                course: "Resistencia de Materiales I",
                idCourse: 1559,
              },
            ],
            section: "1",
            credits: 3.0,
            score: "18",
            status: "Aprobado",
            period: "2020 - 1",
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 5",
        courses: [
          {
            codeCourse: "CI0005",
            course: "Dinámica",
            idCourse: 1558,
            nameTeacher: "Vega Farje, Juan Antonio",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 503,
                namePeriod: "2021 - 2",
                finalNote: 13,
                classroomAverage: 13.68,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "ME3003",
                course: "Estática",
                idCourse: 480,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0024",
                course: "Ingeniería Sismoresistente",
                idCourse: 1998,
              },
            ],
            section: "1",
            credits: 3.0,
            score: "13",
            status: "Aprobado",
            period: "2021 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0006",
            course: "Resistencia de Materiales I",
            idCourse: 1559,
            nameTeacher: "Bedriñana Mera, Luis Alberto",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 402,
                namePeriod: "2021 - 1",
                finalNote: 13,
                classroomAverage: 11.33,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "ME3003",
                course: "Estática",
                idCourse: 480,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0009",
                course: "Resistencia de Materiales II",
                idCourse: 1562,
              },
            ],
            section: "1",
            credits: 3.0,
            score: "13",
            status: "Aprobado",
            period: "2021 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0007",
            course: "Geodesia Satelital y Fotogrametría",
            idCourse: 1560,
            nameTeacher: "Morales Tovar, Jorge Manuel",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 503,
                namePeriod: "2021 - 2",
                finalNote: 17,
                classroomAverage: 17,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CI0001",
                course: "Introducción a la Ingeniería Civil",
                idCourse: 1555,
              },
              {
                codeCourse: "CI0004",
                course: "Geomática",
                idCourse: 1557,
              },
            ],
            afterCourses: [],
            section: "1",
            credits: 4.0,
            score: "17",
            status: "Aprobado",
            period: "2021 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0008",
            course: "Tecnología de los Materiales de Construcción",
            idCourse: 1561,
            nameTeacher: "Corrales Caceres, Jaclyn Luz ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 623,
                namePeriod: "2022 - 1",
                finalNote: 11,
                classroomAverage: 11.74,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CI0001",
                course: "Introducción a la Ingeniería Civil",
                idCourse: 1555,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0022",
                course: "Tecnología del Concreto",
                idCourse: 1670,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "11",
            status: "Aprobado",
            period: "2022 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EG0009",
            course: "Proyectos Interdisciplinarios III",
            idCourse: 959,
            nameTeacher: "Chambilla Aquino, Teófilo ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 503,
                namePeriod: "2021 - 2",
                finalNote: 19,
                classroomAverage: 19,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "EG0008",
                course: "Proyectos Interdisciplinarios II",
                idCourse: 949,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0016",
                course: "Liderazgo y negociación",
                idCourse: 896,
              },
            ],
            section: "8",
            credits: 2.0,
            score: "19",
            status: "Aprobado",
            period: "2021 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0014",
            course: "Culturas de Gobernanza y Distribución de Poder",
            idCourse: 894,
            nameTeacher: "Pizarro Romero, Javier ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 402,
                namePeriod: "2021 - 1",
                finalNote: 14,
                classroomAverage: 15.5,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0012",
                course: "Economías en Desarrollo",
                idCourse: 892,
              },
            ],
            afterCourses: [],
            section: "1",
            credits: 3.0,
            score: "14",
            status: "Aprobado",
            period: "2021 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0025",
            course: "English for STEAM",
            idCourse: 1528,
            nameTeacher: "Cox, Christopher Creighton",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 361,
                namePeriod: "2020 - 2",
                finalNote: 15,
                classroomAverage: 15,
                absences: "3.03%",
              },
            ],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "GH0023",
                course: "Business Communication",
                idCourse: 1526,
              },
            ],
            section: "3",
            credits: 3.0,
            score: "15",
            status: "Aprobado",
            period: "2020 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "ME4003",
            course: "Mecánica de Fluidos",
            idCourse: 40,
            nameTeacher: "Rios Perez, Carlos Alfredo",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 623,
                namePeriod: "2022 - 1",
                finalNote: 11,
                classroomAverage: 12,
                absences: "1.56%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "ME0019",
                course: "Física I",
                idCourse: 924,
              },
              {
                codeCourse: "EG0005",
                course: "Matemáticas II",
                idCourse: 931,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0016",
                course: "Hidráulica Superficial",
                idCourse: 1569,
              },
              {
                codeCourse: "AM0038",
                course: "Hidrología",
                idCourse: 1574,
              },
            ],
            section: "2",
            credits: 4.0,
            score: "11",
            status: "Aprobado",
            period: "2022 - 1",
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 6",
        courses: [
          {
            codeCourse: "AM0038",
            course: "Hidrología",
            idCourse: 1574,
            nameTeacher: "Rau Lavado, Pedro Christopher",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 663,
                namePeriod: "2022 - 2",
                finalNote: 14,
                classroomAverage: 15.57,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "ME4003",
                course: "Mecánica de Fluidos",
                idCourse: 40,
              },
              {
                codeCourse: "IN0054",
                course: "Estadística y Probabilidades",
                idCourse: 946,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0032",
                course: "Infraestructura de Distribución de Agua",
                idCourse: 2006,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "14",
            status: "Aprobado",
            period: "2022 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0009",
            course: "Resistencia de Materiales II",
            idCourse: 1562,
            nameTeacher: "Bedriñana Mera, Luis Alberto",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 623,
                namePeriod: "2022 - 1",
                finalNote: 12,
                classroomAverage: 12.73,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CI0006",
                course: "Resistencia de Materiales I",
                idCourse: 1559,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0014",
                course: "Análisis Estructural I",
                idCourse: 1567,
              },
            ],
            section: "1",
            credits: 3.0,
            score: "12",
            status: "Aprobado",
            period: "2022 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0010",
            course: "Diseño de Infraestructura",
            idCourse: 1563,
            nameTeacher: "Liy Lion, Roger Daniel",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 663,
                namePeriod: "2022 - 2",
                finalNote: 17,
                classroomAverage: 18.57,
                absences: "6.25%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CI0001",
                course: "Introducción a la Ingeniería Civil",
                idCourse: 1555,
              },
            ],
            afterCourses: [],
            section: "1",
            credits: 4.0,
            score: "17",
            status: "Aprobado",
            period: "2022 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0011",
            course: "Ingeniería de Transporte I",
            idCourse: 1564,
            nameTeacher: "Samaniego Barja, Walter ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 503,
                namePeriod: "2021 - 2",
                finalNote: 17,
                classroomAverage: 16,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CI0001",
                course: "Introducción a la Ingeniería Civil",
                idCourse: 1555,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0017",
                course: "Ingeniería de Carreteras",
                idCourse: 1570,
              },
              {
                codeCourse: "CI0036",
                course: "Introducción a la Ingeniería de Tránsito",
                idCourse: 2010,
              },
              {
                codeCourse: "CI0037",
                course: "Sistemas de Tránsito Masivo",
                idCourse: 2011,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "17",
            status: "Aprobado",
            period: "2021 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0012",
            course: "Mecánica de Suelos",
            idCourse: 1565,
            nameTeacher: "Flores Barron, Giancarlo Augusto",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 663,
                namePeriod: "2022 - 2",
                finalNote: 13,
                classroomAverage: 12.15,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CI0001",
                course: "Introducción a la Ingeniería Civil",
                idCourse: 1555,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0018",
                course: "Ingeniería Geotécnica",
                idCourse: 1571,
              },
              {
                codeCourse: "CI0031",
                course: "Ingeniería Geoambiental",
                idCourse: 2005,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "13",
            status: "Aprobado",
            period: "2022 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0015",
            course: "Imagen y Marca Personal",
            idCourse: 895,
            nameTeacher: "Luna Torres, Diana Maria",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 402,
                namePeriod: "2021 - 1",
                finalNote: 15,
                classroomAverage: 16.67,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0010",
                course: "Ética y tecnología",
                idCourse: 890,
              },
              {
                codeCourse: "EG0008",
                course: "Proyectos Interdisciplinarios II",
                idCourse: 949,
              },
            ],
            afterCourses: [
              {
                codeCourse: "GH0016",
                course: "Liderazgo y negociación",
                idCourse: 896,
              },
            ],
            section: "4",
            credits: 3.0,
            score: "15",
            status: "Aprobado",
            period: "2021 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0024",
            course: "Crítica de la Modernidad",
            idCourse: 1527,
            nameTeacher: "Alayza Prager, Cristina ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 503,
                namePeriod: "2021 - 2",
                finalNote: 13,
                classroomAverage: 13.33,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH1002",
                course: "Arte y Tecnología 100 CREDITOS",
                idCourse: 460,
              },
            ],
            afterCourses: [],
            section: "1",
            credits: 3.0,
            score: "13",
            status: "Aprobado",
            period: "2021 - 2",
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 7",
        courses: [
          {
            codeCourse: "CI0013",
            course: "Planeamiento de Proyectos de Construcción",
            idCourse: 1566,
            nameTeacher: "Vilcapoma La Rosa, Alejandro Martin",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 402,
                namePeriod: "2021 - 1",
                finalNote: 15,
                classroomAverage: 16.83,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CI0001",
                course: "Introducción a la Ingeniería Civil",
                idCourse: 1555,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0026",
                course:
                  "Introducción a BIM-Modelado de Información de Construcción",
                idCourse: 2000,
              },
              {
                codeCourse: "CI0027",
                course: "Introducción a Lean Construction",
                idCourse: 2001,
              },
              {
                codeCourse: "CI0028",
                course: "Aspectos Legales en la Construcción",
                idCourse: 2002,
              },
            ],
            section: "1",
            credits: 3.0,
            score: "15",
            status: "Aprobado",
            period: "2021 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0014",
            course: "Análisis Estructural I",
            idCourse: 1567,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [],
            beforeCourses: [
              {
                codeCourse: "CI0009",
                course: "Resistencia de Materiales II",
                idCourse: 1562,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0023",
                course: "Diseño de Concreto Reforzado",
                idCourse: 1997,
              },
              {
                codeCourse: "CI0024",
                course: "Ingeniería Sismoresistente",
                idCourse: 1998,
              },
              {
                codeCourse: "CI0025",
                course: "Diseño de Estructuras Metálicas",
                idCourse: 1999,
              },
            ],
            section: "-",
            credits: 4.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0015",
            course: "Geología General",
            idCourse: 1568,
            nameTeacher: "-",
            times: 1,
            summaryEnrolled: [],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "CI0031",
                course: "Ingeniería Geoambiental",
                idCourse: 2005,
              },
            ],
            section: "-",
            credits: 4.0,
            score: "12",
            status: "Aprobado",
            period: "2022 - 0",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0016",
            course: "Hidráulica Superficial",
            idCourse: 1569,
            nameTeacher: "Guzman Zorrilla, Emanuel Jesus ",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 663,
                namePeriod: "2022 - 2",
                finalNote: 13,
                classroomAverage: 15.54,
                absences: "12.5%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "ME4003",
                course: "Mecánica de Fluidos",
                idCourse: 40,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0032",
                course: "Infraestructura de Distribución de Agua",
                idCourse: 2006,
              },
              {
                codeCourse: "CI0033",
                course: "Ingeniería Costera",
                idCourse: 2007,
              },
              {
                codeCourse: "CI0034",
                course: "Ingeniería de Ríos",
                idCourse: 2008,
              },
            ],
            section: "1",
            credits: 4.0,
            score: "13",
            status: "Aprobado",
            period: "2022 - 2",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0018",
            course: "Ingeniería Geotécnica",
            idCourse: 1571,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [],
            beforeCourses: [
              {
                codeCourse: "CI0012",
                course: "Mecánica de Suelos",
                idCourse: 1565,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0029",
                course: "Ingeniería Geotécnica II",
                idCourse: 2003,
              },
              {
                codeCourse: "CI0030",
                course: "Introducción a la Mecánica de Rocas",
                idCourse: 2004,
              },
            ],
            section: "-",
            credits: 4.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0022",
            course: "Tecnología del Concreto",
            idCourse: 1670,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [
              {
                idPeriod: 744,
                namePeriod: "2023 - 1",
                finalNote: null,
                classroomAverage: 0,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "CI0008",
                course: "Tecnología de los Materiales de Construcción",
                idCourse: 1561,
              },
            ],
            afterCourses: [],
            section: "-",
            credits: 4.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 8",
        courses: [
          {
            codeCourse: "EG0013",
            course: "Proyecto Preprofesional",
            idCourse: 1551,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [
              {
                idPeriod: 744,
                namePeriod: "2023 - 1",
                finalNote: null,
                classroomAverage: 0,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [],
            section: "-",
            credits: 8.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 9",
        courses: [
          {
            codeCourse: "CI0017",
            course: "Ingeniería de Carreteras",
            idCourse: 1570,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [],
            beforeCourses: [
              {
                codeCourse: "CI0011",
                course: "Ingeniería de Transporte I",
                idCourse: 1564,
              },
            ],
            afterCourses: [
              {
                codeCourse: "CI0035",
                course: "Diseño de Pavimentos",
                idCourse: 2009,
              },
            ],
            section: "-",
            credits: 4.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0021",
            course: "Seminarios en Ingeniería Civil",
            idCourse: 1553,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [
              {
                idPeriod: 744,
                namePeriod: "2023 - 1",
                finalNote: null,
                classroomAverage: 0,
                absences: "0%",
              },
            ],
            beforeCourses: [],
            afterCourses: [],
            section: "-",
            credits: 2.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "EG0014",
            course: "Tesis I",
            idCourse: 1552,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [],
            beforeCourses: [],
            afterCourses: [
              {
                codeCourse: "CI0020",
                course: "Tesis II",
                idCourse: 1573,
              },
            ],
            section: "-",
            credits: 4.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "ELECTIVO1",
            course: "ELECTIVO1",
            idCourse: 2000,
            nameTeacher: "Juarez Aquino, Enrique ",
            times: 1,
            summaryEnrolled: [],
            beforeCourses: [],
            afterCourses: [],
            section: "1",
            credits: 3.0,
            score: "17",
            status: "Aprobado",
            period: "2022 - 1",
            syllabus: null,
            isElective: true,
            nameCourseAssociate:
              "Introducción a BIM-Modelado de Información de Construcción",
          },
          {
            codeCourse: "ELECTIVO2",
            course: "ELECTIVO2",
            idCourse: 2002,
            nameTeacher: "Soto Caldas, Grethell Gladys Maria ",
            times: 1,
            summaryEnrolled: [],
            beforeCourses: [],
            afterCourses: [],
            section: "1",
            credits: 3.0,
            score: "14",
            status: "Aprobado",
            period: "2022 - 1",
            syllabus: null,
            isElective: true,
            nameCourseAssociate: "Aspectos Legales en la Construcción",
          },
          {
            codeCourse: "GH0016",
            course: "Liderazgo y negociación",
            idCourse: 896,
            nameTeacher: "Bustamante  Ramos, Hector Gabriel",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 623,
                namePeriod: "2022 - 1",
                finalNote: 15,
                classroomAverage: 15,
                absences: "0%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0015",
                course: "Imagen y Marca Personal",
                idCourse: 895,
              },
              {
                codeCourse: "EG0009",
                course: "Proyectos Interdisciplinarios III",
                idCourse: 959,
              },
            ],
            afterCourses: [],
            section: "5",
            credits: 3.0,
            score: "15",
            status: "Aprobado",
            period: "2022 - 1",
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "GH0023",
            course: "Business Communication",
            idCourse: 1526,
            nameTeacher: "Cox, Christopher Creighton",
            times: 1,
            summaryEnrolled: [
              {
                idPeriod: 503,
                namePeriod: "2021 - 2",
                finalNote: 15,
                classroomAverage: 15,
                absences: "6.45%",
              },
            ],
            beforeCourses: [
              {
                codeCourse: "GH0025",
                course: "English for STEAM",
                idCourse: 1528,
              },
            ],
            afterCourses: [],
            section: "3",
            credits: 2.0,
            score: "15",
            status: "Aprobado",
            period: "2021 - 2",
            syllabus: null,
            isElective: false,
          },
        ],
      },
      {
        title: "Nivel 10",
        courses: [
          {
            codeCourse: "CI0019",
            course: "Gestión de Costos",
            idCourse: 1572,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [],
            beforeCourses: [],
            afterCourses: [],
            section: "-",
            credits: 3.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "CI0020",
            course: "Tesis II",
            idCourse: 1573,
            nameTeacher: "-",
            times: 0,
            summaryEnrolled: [],
            beforeCourses: [
              {
                codeCourse: "EG0014",
                course: "Tesis I",
                idCourse: 1552,
              },
            ],
            afterCourses: [],
            section: "-",
            credits: 6.0,
            score: "-",
            status: "Pendiente",
            period: null,
            syllabus: null,
            isElective: false,
          },
          {
            codeCourse: "ELECTIVO3",
            course: "ELECTIVO3",
            idCourse: 2001,
            nameTeacher: "Juarez Aquino, Enrique ",
            times: 1,
            summaryEnrolled: [],
            beforeCourses: [],
            afterCourses: [],
            section: "1",
            credits: 3.0,
            score: "15",
            status: "Aprobado",
            period: "2022 - 2",
            syllabus: null,
            isElective: true,
            nameCourseAssociate: "Introducción a Lean Construction",
          },
        ],
      },
    ],
  },
};

