const example_utec_api_response = {
  timestamp: 1683113473254,
  uuid: null,
  status: 200,
  error: null,
  message: "OK",
  managed: true,
  content: [
    {
      levelCourse: "7",
      codeCourse: "CI0022",
      course: "Tecnología del Concreto",
      teacher: "Corrales Caceres, Jaclyn Luz ",
      type: "Obligatorio",
      credits: 4.0,
      section: "1",
      nameGroup: "Teoría",
      codeGroup: "1",
      times: "1",
      frequence: "Semana General",
      day: 2,
      starTime: "15:00",
      endTime: "17:00",
      classRoom: "A602(23)",
      period: "2023 - 1",
      levelStudent: "7",
      enrollmentDate: 1679334148000,
      curriculum: "CI-2018-1",
      creditsVirt: 0.0,
      creditsPres: 4.0,
      levelIngles: null,
    },
    {
      levelCourse: "7",
      codeCourse: "CI0022",
      course: "Tecnología del Concreto",
      teacher: "Corrales Caceres, Jaclyn Luz ",
      type: "Obligatorio",
      credits: 4.0,
      section: "1",
      nameGroup: "Laboratorio",
      codeGroup: "1.01",
      times: "1",
      frequence: "Semana A",
      day: 4,
      starTime: "13:00",
      endTime: "17:00",
      classRoom: "L508",
      period: "2023 - 1",
      levelStudent: "7",
      enrollmentDate: 1679334148000,
      curriculum: "CI-2018-1",
      creditsVirt: 0.0,
      creditsPres: 4.0,
      levelIngles: null,
    },
    {
      levelCourse: "7",
      codeCourse: "CI0022",
      course: "Tecnología del Concreto",
      teacher: "Corrales Caceres, Jaclyn Luz ",
      type: "Obligatorio",
      credits: 4.0,
      section: "1",
      nameGroup: "Teoría",
      codeGroup: "1",
      times: "1",
      frequence: "Semana General",
      day: 3,
      starTime: "11:00",
      endTime: "12:00",
      classRoom: "A602(23)",
      period: "2023 - 1",
      levelStudent: "7",
      enrollmentDate: 1679334148000,
      curriculum: "CI-2018-1",
      creditsVirt: 0.0,
      creditsPres: 4.0,
      levelIngles: null,
    },
    {
      levelCourse: "8",
      codeCourse: "EG0013",
      course: "Proyecto Preprofesional",
      teacher: "Caicedo Murillo, Felix Andres ",
      type: "Obligatorio",
      credits: 8.0,
      section: "4",
      nameGroup: "Laboratorio Virtual",
      codeGroup: "4.01",
      times: "1",
      frequence: "Semana General",
      day: 4,
      starTime: "19:00",
      endTime: "21:00",
      classRoom: "Virtual 138",
      period: "2023 - 1",
      levelStudent: "7",
      enrollmentDate: 1679334148000,
      curriculum: "CI-2018-1",
      creditsVirt: 8.0,
      creditsPres: 0.0,
      levelIngles: null,
    },
    {
      levelCourse: "8",
      codeCourse: "EG0013",
      course: "Proyecto Preprofesional",
      teacher: "Caicedo Murillo, Felix Andres ",
      type: "Obligatorio",
      credits: 8.0,
      section: "4",
      nameGroup: "Teoría Virtual",
      codeGroup: "4",
      times: "1",
      frequence: "Semana General",
      day: 2,
      starTime: "19:00",
      endTime: "21:00",
      classRoom: "Virtual 137",
      period: "2023 - 1",
      levelStudent: "7",
      enrollmentDate: 1679334148000,
      curriculum: "CI-2018-1",
      creditsVirt: 8.0,
      creditsPres: 0.0,
      levelIngles: null,
    },
    {
      levelCourse: "9",
      codeCourse: "CI0021",
      course: "Seminarios en Ingeniería Civil",
      teacher: "Caicedo Murillo, Felix Andres ",
      type: "Obligatorio",
      credits: 2.0,
      section: "1",
      nameGroup: "Teoría",
      codeGroup: "1",
      times: "1",
      frequence: "Semana General",
      day: 1,
      starTime: "19:00",
      endTime: "21:00",
      classRoom: "A704(47)",
      period: "2023 - 1",
      levelStudent: "7",
      enrollmentDate: 1679334148000,
      curriculum: "CI-2018-1",
      creditsVirt: 0.0,
      creditsPres: 2.0,
      levelIngles: null,
    },
  ],
};

export const fetchCurrentCurriculumId = async ({
  utec_token_v1,
}: {
  utec_token_v1: string;
}) => {
  const res_get_curriculum = await fetch(
    "https://api.utec.edu.pe/academico-api/alumnos/me/consolidated/enrollment",
    {
      method: "POST",
      headers: {
        "x-auth-token": utec_token_v1,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        hello: "world",
      }),
    }
  );

  if (res_get_curriculum.status !== 200) {
    throw new Error("Error al obtener el curriculum");
  }

  const data_get_curriculum =
    (await res_get_curriculum.json()) as typeof example_utec_api_response;

  let current_curriculum_handle = data_get_curriculum.content[0].curriculum;

  current_curriculum_handle = current_curriculum_handle.replace(/\s/g, "");
  current_curriculum_handle = current_curriculum_handle.trim();

  return current_curriculum_handle;
};
