export const example_response = {
  timestamp: 1682798533834,
  uuid: null,
  status: 200,
  error: null,
  message: "OK",
  managed: true,
  content: [
    {
      id: 744,
      label: "2023 - 1",
      orderMerit: " - ",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "EG0013",
          idCourse: 1551,
          idStorage: null,
          nameFile: null,
          career: null,
          faculty: null,
          course: "Proyecto Preprofesional",
          credits: 8,
          level: "Nivel 8",
          score: "-",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0021",
          idCourse: 1553,
          idStorage: null,
          nameFile: null,
          career: null,
          faculty: null,
          course: "Seminarios en Ingeniería Civil",
          credits: 2,
          level: "Nivel 9",
          score: "-",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0022",
          idCourse: 1670,
          idStorage: null,
          nameFile: null,
          career: null,
          faculty: null,
          course: "Tecnología del Concreto",
          credits: 4,
          level: "Nivel 7",
          score: "-",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 663,
      label: "2022 - 2",
      weightedAverage: 14.37,
      orderMerit: "194 de 534",
      ranking: "MEDIO",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "CI0010",
          idCourse: 1563,
          idStorage: "1JxTidaZ38wuSwC3ZaM8tAKHrP0H7pwxf",
          nameFile: "CI0010_2022 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Diseño de Infraestructura",
          credits: 4,
          level: "Nivel 6",
          score: "17",
          absences: "6.25%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "AM0038",
          idCourse: 1574,
          idStorage: null,
          nameFile: null,
          career: null,
          faculty: null,
          course: "Hidrología",
          credits: 4,
          level: "Nivel 6",
          score: "14",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0016",
          idCourse: 1569,
          idStorage: "1FBSV2PlBSddkepJTMhH3B8AEBS6Z7Zz7",
          nameFile: "CI0016_2022 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Hidráulica Superficial",
          credits: 4,
          level: "Nivel 7",
          score: "13",
          absences: "12.5%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0027",
          idCourse: 2001,
          idStorage: "10FmUnO2IcxizV-Z1pdGluAO3anfQU17f",
          nameFile: "CI0027_2022 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Introducción a Lean Construction",
          credits: 3,
          level: "Cursos Electivos",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0012",
          idCourse: 1565,
          idStorage: "1qBPVuoI8oZXZyoX4AJLYIiLfXKudHblH",
          nameFile: "CI0012_2022 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Mecánica de Suelos",
          credits: 4,
          level: "Nivel 6",
          score: "13",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 623,
      label: "2022 - 1",
      weightedAverage: 13.1,
      orderMerit: "281 de 460",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "CI0028",
          idCourse: 2002,
          idStorage: "1zt0GN1OV_-Tphcdl2PDljp0Us5r8e6GJ",
          nameFile: "CI0028_2022 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Aspectos Legales en la Construcción",
          credits: 3,
          level: "Cursos Electivos",
          score: "14",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0026",
          idCourse: 2000,
          idStorage: "1RlJLeWjIsHIpTEM7r97BLUtOYUg0s8IA",
          nameFile: "CI0026_2022 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Introducción a BIM-Modelado de Información de Construcción",
          credits: 3,
          level: "Cursos Electivos",
          score: "17",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0016",
          idCourse: 896,
          idStorage: "1w4m9Z6H8OqovnpRDkhln4fNTJyqWth0i",
          nameFile: "GH0016_2022 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Liderazgo y negociación",
          credits: 3,
          level: "Nivel 9",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "ME4003",
          idCourse: 40,
          idStorage: "1ULA7F1qc7WLxzt7FH6YSFfj_rjLDitcv",
          nameFile: "ME4003_2022 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Mecánica de Fluidos",
          credits: 4,
          level: "Nivel 5",
          score: "11",
          absences: "1.56%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0009",
          idCourse: 1562,
          idStorage: "1pX1wYDSr5f2DBM6S8PWrTQ_NJ-KJmKSC",
          nameFile: "CI0009_2022 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Resistencia de Materiales II",
          credits: 3,
          level: "Nivel 6",
          score: "12",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0008",
          idCourse: 1561,
          idStorage: "1Wb2w-Vkr9yNlhr0-hgzqwTzbTyaZEjUm",
          nameFile: "CI0008_2022 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Tecnología de los Materiales de Construcción",
          credits: 4,
          level: "Nivel 5",
          score: "11",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 603,
      label: "2022 - 0",
      weightedAverage: 12,
      orderMerit: "131 de 170",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "AM0010",
          idCourse: 1013,
          idStorage: "1j4B-PaNBw5EjpdlPZoZBiplT-YkQzrUr",
          nameFile: "AM0010_2022 - 0_ES.pdf",
          career: null,
          faculty: null,
          course: "Geologia General",
          credits: 4,
          level: "Otra malla",
          score: "12",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 503,
      label: "2021 - 2",
      weightedAverage: 15.67,
      orderMerit: "119 de 432",
      ranking: "TERCIO",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "GH0023",
          idCourse: 1526,
          idStorage: "1G6Un6BMiTA5s6UAyok3Sw631H6Zb8vxs",
          nameFile: "gh002320212espdf.pdf",
          career: null,
          faculty: null,
          course: "Business Communication",
          credits: 2,
          level: "Nivel 9",
          score: "15",
          absences: "6.45%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0024",
          idCourse: 1527,
          idStorage: "1ykJ5MpLAeprlH79233Sh-g0B6PTMjOGY",
          nameFile: "gh002420212espdf.pdf",
          career: null,
          faculty: null,
          course: "Crítica de la Modernidad",
          credits: 3,
          level: "Nivel 6",
          score: "13",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0005",
          idCourse: 1558,
          idStorage: "1YL3jIgxwZ08U-PzzAN8MHrKHEwQ9eBDs",
          nameFile: "ci000520212espdf.pdf",
          career: null,
          faculty: null,
          course: "Dinámica",
          credits: 3,
          level: "Nivel 5",
          score: "13",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0007",
          idCourse: 1560,
          idStorage: "1CxbOBuddNEUC_XcqCn0AFsS3GMW3X4qX",
          nameFile: "ci000720212espdf.pdf",
          career: null,
          faculty: null,
          course: "Geodesia Satelital y Fotogrametría",
          credits: 4,
          level: "Nivel 5",
          score: "17",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0011",
          idCourse: 1564,
          idStorage: "1PZRCmFYUm_y7iMqdOAwAShx4_StFURlL",
          nameFile: "ci001120212espdf.pdf",
          career: null,
          faculty: null,
          course: "Ingeniería de Transporte I",
          credits: 4,
          level: "Nivel 6",
          score: "17",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "ME4003",
          idCourse: 40,
          idStorage: "1ieEJBEMkw5kQgFRnExGNfR34A-ZnRIJt",
          nameFile: "me400320212espdf.pdf",
          career: null,
          faculty: null,
          course: "Mecánica de Fluidos",
          credits: 4,
          level: "Nivel 5",
          score: "-",
          absences: "3.17%",
          times: 1,
          status: "Retirado",
        },
        {
          codeCourse: "EG0009",
          idCourse: 959,
          idStorage: "1xz-rnjsbE3RapfyWnuQkVabuUY8OnCUb",
          nameFile: "eg000920212espdf.pdf",
          career: null,
          faculty: null,
          course: "Proyectos Interdisciplinarios III",
          credits: 2,
          level: "Nivel 5",
          score: "19",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 402,
      label: "2021 - 1",
      weightedAverage: 15.14,
      orderMerit: "90 de 259",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "GH0014",
          idCourse: 894,
          idStorage: "1XwuN5y7Yxpt3RhbuTEQjIO_itN6Gv15k",
          nameFile: "GH0014_2021 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Culturas de Gobernanza y Distribución de Poder",
          credits: 3,
          level: "Nivel 5",
          score: "14",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "IN0054",
          idCourse: 946,
          idStorage: "1hDJI8DkAj81wX1N5L6BxJtoJKimwACcq",
          nameFile: "IN0054_2021 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Estadística y Probabilidades",
          credits: 4,
          level: "Nivel 3",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0004",
          idCourse: 1557,
          idStorage: "1tIHBwYrmK5F_y-8aL2mhMiIHYZw6tzRJ",
          nameFile: "CI0004_2021 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Geomática",
          credits: 4,
          level: "Nivel 4",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0015",
          idCourse: 895,
          idStorage: "1YbBerWFXtUwKAvmbCJy6Mzb5c5oM_zyJ",
          nameFile: "GH0015_2021 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Imagen y Marca Personal",
          credits: 3,
          level: "Nivel 6",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0011",
          idCourse: 891,
          idStorage: "1msiC9rSXpo1p8UEyehxh60PjE6uz69YJ",
          nameFile: "GH0011_2021 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Innovación y Desarrollo de Productos",
          credits: 2,
          level: "Nivel 4",
          score: "19",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0013",
          idCourse: 1566,
          idStorage: "1-FfXEvz13SJC_DQyF-dmJVi2qO-ZekUp",
          nameFile: "CI0013_2021 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Planeamiento de Proyectos de Construcción",
          credits: 3,
          level: "Nivel 7",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0006",
          idCourse: 1559,
          idStorage: "1nvRfyX4zxn55j9cCQvoEC5cDN1Pa-p-q",
          nameFile: "CI0006_2021 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Resistencia de Materiales I",
          credits: 3,
          level: "Nivel 5",
          score: "13",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0008",
          idCourse: 1561,
          idStorage: "1WMb37NlHRDeICEyr29TbRKeKNzadIlo_",
          nameFile: "CI0008_2021 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Tecnología de los Materiales de Construcción",
          credits: 4,
          level: "Nivel 5",
          score: "-",
          absences: "4%",
          times: 1,
          status: "Retirado",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 401,
      label: "2021 - 0",
      weightedAverage: 18,
      orderMerit: "7 de 115",
      ranking: "DECIMO",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "GH0012",
          idCourse: 892,
          idStorage: "1oHWAs0a7F_bC6nuTDskzhnlIwC_z5W4Y",
          nameFile: "GH0012_2021 - 0_ES.pdf",
          career: null,
          faculty: null,
          course: "Economías en Desarrollo",
          credits: 3,
          level: "Nivel 4",
          score: "18",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 361,
      label: "2020 - 2",
      weightedAverage: 16.68,
      orderMerit: "37 de 192",
      ranking: "QUINTO",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "GH0025",
          idCourse: 1528,
          idStorage: "1AiY3gf6eZy4VUXz8UbGp0Jz-rVp7UQLR",
          nameFile: "GH0025_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "English for STEAM",
          credits: 3,
          level: "Nivel 5",
          score: "15",
          absences: "3.03%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0002",
          idCourse: 1554,
          idStorage: "1LS4JsE-zI1Ne48ZGr0gU--X5y-Hk3W_c",
          nameFile: "CI0002_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Geometría Descriptiva",
          credits: 4,
          level: "Nivel 3",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0008",
          idCourse: 888,
          idStorage: "1vsdkXocaAgWUo-pgoZpk1NW5YYwRLiMb",
          nameFile: "GH0008_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Gestión de Empresas",
          credits: 2,
          level: "Nivel 3",
          score: "19",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0001",
          idCourse: 1555,
          idStorage: "1ZanivO9dNCuJwP_sLbFZ13GOT0vZ2EZd",
          nameFile: "CI0001_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Introducción a la Ingeniería Civil",
          credits: 3,
          level: "Nivel 4",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "EG0006",
          idCourse: 943,
          idStorage: "17Py_6P_VjyV2dKZ-24EaUrE3oa52dGe0",
          nameFile: "EG0006_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Matemáticas III",
          credits: 4,
          level: "Nivel 3",
          score: "18",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0009",
          idCourse: 889,
          idStorage: "1WihbyNxX0E8bPru29wHxL9mKypr7t3c8",
          nameFile: "GH0009_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Perú: ¿País Industrial?",
          credits: 2,
          level: "Nivel 3",
          score: "13",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "EG0008",
          idCourse: 949,
          idStorage: "1u2TOuZHNZscUH-bZehMrmJ8WgEA-5pTN",
          nameFile: "EG0008_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Proyectos Interdisciplinarios II",
          credits: 2,
          level: "Nivel 4",
          score: "19",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CI0003",
          idCourse: 1556,
          idStorage: "1lb9leeiieUG7hC7gZTWxeMDgOwn5sjic",
          nameFile: "CI0003_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Tecnologías Aplicadas y Mega Proyectos en Ingeniería Civil",
          credits: 3,
          level: "Nivel 4",
          score: "19",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0010",
          idCourse: 890,
          idStorage: "1ZOrgH_Uu0tmm778M9cdVm-r0AiQX1-Tg",
          nameFile: "GH0010_2020 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Ética y tecnología",
          credits: 2,
          level: "Nivel 4",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 241,
      label: "2020 - 1",
      weightedAverage: 16.72,
      orderMerit: "17 de 141",
      ranking: "QUINTO",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "ME3003",
          idCourse: 480,
          idStorage: "1QDsv3MDoop-EyTcdJ74V6WZEZAbJoHf4",
          nameFile: "ME3003_2020 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Estática",
          credits: 3,
          level: "Nivel 4",
          score: "18",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0007",
          idCourse: 887,
          idStorage: "14utQ1Jrqw5icuX3CTDX-PLhYFSt_H2dD",
          nameFile: "GH0007_2020 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Introducción al Desarrollo de Empresas",
          credits: 2,
          level: "Nivel 2",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0006",
          idCourse: 886,
          idStorage: "1YdjSLQ5LGrb4u8XsI1kB2V2YhhhmiWxS",
          nameFile: "GH0006_2020 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Laboratorio de Comunicación 2",
          credits: 3,
          level: "Nivel 2",
          score: "17",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "EG0005",
          idCourse: 931,
          idStorage: "15M48Aoscx2bfDZ84577DcJtD-HoYLadx",
          nameFile: "EG0005_2020 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Matemáticas II",
          credits: 4,
          level: "Nivel 2",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "EG0007",
          idCourse: 947,
          idStorage: "1Aia5pOQhGNRYXp-5L3HIuosczr8mXMew",
          nameFile: "EG0007_2020 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Proyectos Interdisciplinarios I",
          credits: 2,
          level: "Nivel 3",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "ME0021",
          idCourse: 945,
          idStorage: "13PY_WUO2AIMZzZ5500krabDiOun9MJWk",
          nameFile: "ME0021_2020 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Termodinámica",
          credits: 4,
          level: "Nivel 3",
          score: "17",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 341,
      label: "2020 - 0",
      weightedAverage: 15,
      orderMerit: "24 de 59",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "GH1002",
          idCourse: 460,
          idStorage: "1qZiCWUyq_58M0gdJgCKGu7Av-W0ZFezl",
          nameFile: "GH1002_2020 - 0_ES.pdf",
          career: null,
          faculty: null,
          course: "Arte y Tecnología",
          credits: 1,
          level: "Nivel 2",
          score: "19",
          absences: "12.5%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "EN0021",
          idCourse: 932,
          idStorage: "1IikQgSR4TGL3RWGJsZeWYz-E2zWhss-7",
          nameFile: "EN0021_2020 - 0_ES.pdf",
          career: null,
          faculty: null,
          course: "Física II",
          credits: 4,
          level: "Nivel 2",
          score: "14",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 223,
      label: "2019 - 2",
      weightedAverage: 15.84,
      orderMerit: "23 de 105",
      ranking: "TERCIO",
      curriculum: "CI-2018-1",
      data: [
        {
          codeCourse: "AM0037",
          idCourse: 1304,
          idStorage: "1MwiHA2-3rpBK0JIgEB95nAuUbP9Vqo-B",
          nameFile: "AM0037_2019 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Ciencia de los Materiales",
          credits: 4,
          level: "Nivel 2",
          score: "17",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "ME0019",
          idCourse: 924,
          idStorage: "1SfWzntQ-BHBqBGQOfj4HsmpShv35krK7",
          nameFile: "ME0019_2019 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Física I",
          credits: 4,
          level: "Nivel 1",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GH0005",
          idCourse: 885,
          idStorage: "1R4Jo7JB6AT5FH7602ZghjY423A1vR0eO",
          nameFile: "GH0005_2019 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Laboratorio de Comunicación 1",
          credits: 3,
          level: "Nivel 1",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "EG0003",
          idCourse: 923,
          idStorage: "1btAgcPQaosn3I6AA7P3eljtnaU_r-ouy",
          nameFile: "EG0003_2019 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Matemáticas I",
          credits: 4,
          level: "Nivel 1",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CS1102",
          idCourse: 1057,
          idStorage: "1fYi9UDdmtndw2oPIVD4SMsRmYmmg-XnJ",
          nameFile: "CS1102_2019 - 2_ES.pdf",
          career: null,
          faculty: null,
          course: "Programación orientada a objetos I",
          credits: 4,
          level: "Nivel 2",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Civil",
      faculty: "Facultad de Ingeniería ",
    },
    {
      id: 222,
      label: "2019 - 1",
      weightedAverage: 15.45,
      orderMerit: "23 de 101",
      ranking: "TERCIO",
      curriculum: "AM-2018-1",
      data: [
        {
          codeCourse: "EGN001",
          idCourse: 1550,
          idStorage: "1sxBCTwrMumHkv4JHMDtaQqaph7ZCwxIM",
          nameFile: "EGN001_2019 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Ciencias 0",
          credits: 0,
          level: "Nivel 0",
          score: "17",
          absences: "3.13%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "EG0004",
          idCourse: 928,
          idStorage: "1E8s17V1AFOXvaNTJWA3U189zHnR8oETd",
          nameFile: "EG0004_2019 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Desafíos Globales",
          credits: 3,
          level: "Nivel 1",
          score: "16",
          absences: ".95%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "CS1100",
          idCourse: 1055,
          idStorage: "10d0IH4B_gChoc9P5o_Pgv8mqmwJOPCX6",
          nameFile: "CS1100_2019 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Introducción a la Ciencia de la Computación",
          credits: 4,
          level: "Nivel 1",
          score: "15",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "GHN004",
          idCourse: 884,
          idStorage: "1RTJSvcmYj7z-h2ySCa7T5-Q07F0tn-0m",
          nameFile: "GHN004_2019 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Laboratorio de Comunicación 0",
          credits: 0,
          level: "Nivel 0",
          score: "15",
          absences: "6.25%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "QI0028",
          idCourse: 930,
          idStorage: "1Jilnb0f6BygMxKpoImrmL5aLtljfIMlg",
          nameFile: "QI0028_2019 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Química Experimental",
          credits: 1,
          level: "Nivel 1",
          score: "14",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
        {
          codeCourse: "QI0027",
          idCourse: 925,
          idStorage: "14wtOkdo7jllYnVuwpkKMg6H7zR7OHBG1",
          nameFile: "QI0027_2019 - 1_ES.pdf",
          career: null,
          faculty: null,
          course: "Química General",
          credits: 3,
          level: "Nivel 1",
          score: "16",
          absences: "0%",
          times: 1,
          status: "Activo",
        },
      ],
      career: "Ingeniería Ambiental",
      faculty: "Facultad de Ingeniería ",
    },
  ],
};
